USE [SecurityMaster]
GO

CREATE  PROCEDURE UpdateBond
(
@SecurityId INT,
@BondDescription	VARCHAR(MAX),
@AssetType	VARCHAR(MAX),
@InvestmentType	VARCHAR(MAX),
@TradingFactor	VARCHAR(MAX),
@PricingFactor	VARCHAR(MAX),
@ISIN	VARCHAR(MAX),
@BBG_Ticker	VARCHAR(MAX),
@BBG_UniqueID	VARCHAR(MAX),
@CUSIP	VARCHAR(MAX),
@SEDOL	VARCHAR(MAX),
@FirstCouponDate	DATETIME,
@Cap	VARCHAR(MAX),
@BondFloor	VARCHAR(MAX),
@CouponFrequency	VARCHAR(MAX),
@Coupon	VARCHAR(MAX),
@CouponType	VARCHAR(MAX),
@Spread	VARCHAR(MAX),
@CallableFlag	BIT,
@FixToFloatFlag	BIT,
@PutableFlag	BIT,
@IssueDate	DATETIME,
@LastResetDate	DATETIME,
@Maturity	DATETIME,
@CallNotificationMaxDays	VARCHAR(MAX),
@PutNotificationMaxDays	VARCHAR(MAX),
@PenultimateCouponDate	DATETIME,
@ResetFrequency	VARCHAR(MAX),
@HasPosition	BIT,
@MacaulayDuration	VARCHAR(MAX),
@Volatility_30D	VARCHAR(MAX),
@Volatility_90D	VARCHAR(MAX),
@Convexity	VARCHAR(MAX),
@AverageVolume_30D	VARCHAR(MAX),
@PF_AssetClass	VARCHAR(MAX),
@PF_Country	VARCHAR(MAX),
@PF_CreditRating	VARCHAR(MAX),
@PF_Currency	VARCHAR(MAX),
@PF_Instrument	VARCHAR(MAX),
@PF_LiquidityProfile	VARCHAR(MAX),
@PF_Maturity	VARCHAR(MAX),
@PF_NAICS_Code	VARCHAR(MAX),
@PF_Region	VARCHAR(MAX),
@PF_Sector	VARCHAR(MAX),
@PF_SubAssetClass	VARCHAR(MAX),
@BBG_IndustryGroup	VARCHAR(MAX),
@BBG_IndustrySubGroup	VARCHAR(MAX),
@BBG_IndustrySector	VARCHAR(MAX),
@CountryOfIssuance	VARCHAR(MAX),
@IssueCurrency	VARCHAR(MAX),
@Issuer	VARCHAR(MAX),
@RiskCurrency	VARCHAR(MAX),
@PutDate	DATETIME,
@PutPrice	VARCHAR(MAX),
@AskPrice	VARCHAR(MAX),
@HighPrice	VARCHAR(MAX),
@LowPrice	VARCHAR(MAX),
@OpenPrice	VARCHAR(MAX),
@Volume	VARCHAR(MAX),
@BidPrice	VARCHAR(MAX),
@LastPrice	VARCHAR(MAX),
@CallDate	DATETIME,
@CallPrice	VARCHAR(MAX)
)
AS
BEGIN
  UPDATE dbo.CorporateBond
  SET
	BondDescription=ISNULL(@BondDescription, BondDescription),
	AssetType=ISNULL(@AskPrice ,AssetType),
	InvestmentType=ISNULL(@InvestmentType,InvestmentType),
	TradingFactor=ISNULL(@TradingFactor,TradingFactor),
	PricingFactor=ISNULL(@PricingFactor,PricingFactor),
	ISIN=ISNULL(@ISIN,ISIN),
	BBG_Ticker=ISNULL(@BBG_Ticker,BBG_Ticker),
	BBG_UniqueID=ISNULL(@BBG_UniqueID,BBG_UniqueID),
	CUSIP=ISNULL(@CUSIP,CUSIP),
	SEDOL=ISNULL(@SEDOL,SEDOL),
	FirstCouponDate=ISNULL(@FirstCouponDate,FirstCouponDate),
	Cap=ISNULL(@Cap,Cap),
	BondFloor=ISNULL(@BondFloor,BondFloor),
	CouponFrequency=ISNULL(@CouponFrequency,CouponFrequency),
	Coupon=ISNULL(@Coupon,Coupon),
	CouponType=ISNULL(@CouponType,CouponType),
	Spread=ISNULL(@Spread,Spread),
	CallableFlag=ISNULL(@CallableFlag,CallableFlag),
	FixToFloatFlag=ISNULL(@FixToFloatFlag,FixToFloatFlag),
	PutableFlag=ISNULL(@PutableFlag,PutableFlag),
	IssueDate=ISNULL(@IssueDate,IssueDate),
	LastResetDate=ISNULL(@LastResetDate,LastResetDate),
	Maturity=ISNULL(@Maturity,Maturity),
	CallNotificationMaxDays=ISNULL(@CallNotificationMaxDays,CallNotificationMaxDays),
	PutNotificationMaxDays=ISNULL(@PutNotificationMaxDays,PutNotificationMaxDays),
	PenultimateCouponDate=ISNULL(@PenultimateCouponDate,PenultimateCouponDate),
	ResetFrequency=ISNULL(@ResetFrequency,ResetFrequency),
	HasPosition=ISNULL(@HasPosition,HasPosition),
	MacaulayDuration=ISNULL(@MacaulayDuration,MacaulayDuration),
	Volatility_30D=ISNULL(@Volatility_30D,Volatility_30D),
	Volatility_90D=ISNULL(@Volatility_90D,Volatility_90D),
	Convexity=ISNULL(@Convexity,Convexity),
	AverageVolume_30D=ISNULL(@AverageVolume_30D,AverageVolume_30D),
	PF_AssetClass=ISNULL(@PF_AssetClass,PF_AssetClass),
	PF_Country=ISNULL(@PF_Country,PF_Country),
	PF_CreditRating=ISNULL(@PF_CreditRating,PF_CreditRating),
	PF_Currency=ISNULL(@PF_Currency,PF_Currency),
	PF_Instrument=ISNULL(@PF_Instrument,PF_Instrument),
	PF_LiquidityProfile=ISNULL(@PF_LiquidityProfile,PF_LiquidityProfile),
	PF_Maturity=ISNULL(@PF_Maturity,PF_Maturity),
	PF_NAICS_Code=ISNULL(@PF_NAICS_Code,PF_NAICS_Code),
	PF_Region=ISNULL(@PF_Region,PF_Region),
	PF_Sector=ISNULL(@PF_Sector,PF_Sector),
	PF_SubAssetClass=ISNULL(@PF_SubAssetClass,PF_SubAssetClass),
	BBG_IndustryGroup=ISNULL(@BBG_IndustryGroup,BBG_IndustryGroup),
	BBG_IndustrySubGroup=ISNULL(@BBG_IndustrySubGroup,BBG_IndustrySubGroup),
	BBG_IndustrySector=ISNULL(@BBG_IndustrySector,BBG_IndustrySector),
	CountryOfIssuance=ISNULL(@CountryOfIssuance,CountryOfIssuance),
	IssueCurrency=ISNULL(@IssueCurrency,IssueCurrency),
	Issuer=ISNULL(@Issuer,Issuer),
	RiskCurrency=ISNULL(@RiskCurrency,RiskCurrency),
	PutDate=ISNULL(@PutDate,PutDate),
	PutPrice=ISNULL(@PutPrice,PutPrice),
	AskPrice=ISNULL(@AskPrice,AskPrice),
	HighPrice=ISNULL(@HighPrice,HighPrice),
	LowPrice=ISNULL(@LowPrice,LowPrice),
	OpenPrice=ISNULL(@OpenPrice,OpenPrice),
	Volume=ISNULL(@Volume,Volume),
	BidPrice=ISNULL(@BidPrice,BidPrice),
	LastPrice=ISNULL(@LastPrice,LastPrice),
	CallDate=ISNULL(@CallDate,CallDate),
	CallPrice=ISNULL(@CallPrice,CallPrice)
	WHERE SecurityId=@SecurityId
END