USE [SecurityMaster]
GO

CREATE  PROCEDURE UpdateEquity
(
@securityId int,
@equityDescription VARCHAR(MAX),
@hasPosition BIT,
@isActiveSecurity BIT,
@lotSize VARCHAR(MAX),
@BBG_UniqueName VARCHAR(MAX),
@CUSIP VARCHAR(MAX),
@ISIN VARCHAR(MAX),
@SEDOL VARCHAR(MAX),
@BBG_Ticker VARCHAR(MAX),
@BBG_UniqueId VARCHAR(MAX),
@BBG_GlobalId VARCHAR(MAX),
@tickerAndExchange VARCHAR(MAX),
@isADR BIT,
@ADR_underlyingTicker VARCHAR(MAX),
@ADR_underlyingCurrency VARCHAR(MAX),
@sharesPerADR VARCHAR(MAX),
@IPODate DATETIME,
@pricingCurrency VARCHAR(MAX),
@settleDays VARCHAR(MAX),
@totalSharesOutstanding VARCHAR(MAX),
@votingRightsPerShare VARCHAR(MAX),
@averageVolume_20D VARCHAR(MAX),
@beta VARCHAR(MAX),
@shortInterest VARCHAR(MAX),
@return_YTD VARCHAR(MAX),
@volatility_90D VARCHAR(MAX),
@PF_AssetClass VARCHAR(MAX),
@PF_Country VARCHAR(MAX),
@PF_CreditRating VARCHAR(MAX),
@PF_Currency VARCHAR(MAX),
@PF_Instrument VARCHAR(MAX),
@PF_LiquidityProfile VARCHAR(MAX),
@PF_Maturity VARCHAR(MAX),
@PF_NAICS_Code VARCHAR(MAX),
@PF_Region VARCHAR(MAX),
@PF_Sector VARCHAR(MAX),
@PF_SubAssetClass VARCHAR(MAX),
@countryOfIssuance VARCHAR(MAX),
@exchange VARCHAR(MAX),
@issuer VARCHAR(MAX),
@issueCurrency VARCHAR(MAX),
@tradingCurrency VARCHAR(MAX),
@BBG_industrySubGroup VARCHAR(MAX),
@BBG_industryGroup VARCHAR(MAX),
@BBG_sector VARCHAR(MAX),
@countryOfIncorporation VARCHAR(MAX),
@riskCurrency VARCHAR(MAX),
@openPrice VARCHAR(MAX),
@closePrice VARCHAR(MAX),
@volume VARCHAR(MAX),
@lastPrice VARCHAR(MAX),
@askPrice VARCHAR(MAX),
@bidPrice VARCHAR(MAX),
@PE_Ratio VARCHAR(MAX),
@dividendDeclaredDate DATETIME,
@dividendExDate DATETIME,
@dividendRecordDate DATETIME,
@dividendPayDate DATETIME,
@dividendAmount VARCHAR(MAX),
@frequency VARCHAR(MAX),
@dividendType VARCHAR(MAX)
)
AS
BEGIN
	UPDATE dbo.Equity
	SET
	EquityDescription = ISNULL(@equityDescription, EquityDescription),
	HasPosition = ISNULL(@hasPosition, HasPosition),
	IsActiveSecurity = ISNULL(@isActiveSecurity, IsActiveSecurity),
	LotSize = ISNULL(@lotSize, LotSize),
	BBG_UniqueName = ISNULL(@BBG_UniqueName, @BBG_UniqueName),
	CUSIP = ISNULL(@CUSIP, CUSIP),
	ISIN = ISNULL(@ISIN, ISIN),
	SEDOL = ISNULL(@SEDOL, SEDOL),
	BBG_Ticker = ISNULL(@BBG_Ticker, @BBG_Ticker),
	BBG_UniqueID = ISNULL(@BBG_UniqueId, BBG_UniqueID),
	BBG_GlobalID = ISNULL(@BBG_GlobalId, BBG_GlobalID),
	TickerAndExchange = ISNULL(@tickerAndExchange, TickerAndExchange),
	IsAdrFlag = ISNULL(@isADR, IsAdrFlag),
	AdrUnderlyingTicker = ISNULL(@ADR_underlyingTicker, AdrUnderlyingTicker),
	AdrUnderlyingCurrency = ISNULL(@ADR_underlyingCurrency, AdrUnderlyingCurrency),
	SharesPerADR = ISNULL(@sharesPerADR, SharesPerADR),
	IPODate = ISNULL(@IPODate, IPODate),
	PricingCurrency = ISNULL(@pricingCurrency, PricingCurrency),
	SettleDays = ISNULL(@settleDays, SettleDays),
	TotalSharesOutstanding = ISNULL(@totalSharesOutstanding, TotalSharesOutstanding),
	VotingRightsPerShare = ISNULL(@votingRightsPerShare, VotingRightsPerShare),
	AverageVolume_20D = ISNULL(@averageVolume_20D, AverageVolume_20D),
	Beta = ISNULL(@beta, Beta),
	ShortInterest = ISNULL(@shortInterest, ShortInterest),
	Return_YTD = ISNULL(@return_YTD, Return_YTD),
	Volatility_90D = ISNULL(@volatility_90D, Volatility_90D),
	PF_AssetClass = ISNULL(@PF_AssetClass, PF_AssetClass),
	PF_Country = ISNULL(@PF_Country, PF_Country),
	PF_CreditRating = ISNULL(@PF_CreditRating, PF_CreditRating),
	PF_Currency = ISNULL(@PF_Currency, PF_Currency),
	PF_Instrument = ISNULL(@PF_Instrument, PF_Instrument),
	PF_LiquidityProfile = ISNULL(@PF_LiquidityProfile, PF_LiquidityProfile),
	PF_Maturity = ISNULL(@PF_Maturity, PF_Maturity),
	PF_NAICS_Code = ISNULL(@PF_NAICS_Code, PF_NAICS_Code),
	PF_Region = ISNULL(@PF_Region, PF_Region),
	PF_Sector = ISNULL(@PF_Sector, PF_Sector),
	PF_SubAssetClass = ISNULL(@PF_SubAssetClass, PF_SubAssetClass),
	CountryOfIssuance = ISNULL(@countryOfIssuance, CountryOfIssuance),
	Exchange = ISNULL(@exchange, Exchange),
	Issuer = ISNULL(@issuer, Issuer),
	IssueCurrency = ISNULL(@issueCurrency, IssueCurrency),
	TradingCurrency = ISNULL(@tradingCurrency, TradingCurrency),
	BBG_IndustrySubGroup = ISNULL(@BBG_industrySubGroup, BBG_IndustrySubGroup),
	BBG_IndustryGroup = ISNULL(@BBG_industryGroup, BBG_IndustryGroup),
	BBG_Sector = ISNULL(@BBG_sector, BBG_Sector),
	CountryOfIncorporation = ISNULL(@countryOfIncorporation, CountryOfIncorporation),
	RiskCurrency = ISNULL(@riskCurrency, RiskCurrency),
	OpenPrice = ISNULL(@openPrice, OpenPrice),
	ClosePrice = ISNULL(@closePrice, ClosePrice),
	Volume = ISNULL(@volume, Volume),
	LastPrice = ISNULL(@lastPrice, LastPrice),
	AskPrice = ISNULL(@askPrice, AskPrice),
	BidPrice = ISNULL(@bidPrice, BidPrice),
	PE_Ratio = ISNULL(@PE_Ratio, PE_Ratio),
	DividendDeclaredDate = ISNULL(@dividendDeclaredDate, DividendDeclaredDate),
	DividendExDate = ISNULL(@dividendExDate, DividendExDate),
	DividendRecordDate = ISNULL(@dividendRecordDate, DividendRecordDate),
	DividendPayDate = ISNULL(@dividendPayDate, DividendPayDate),
	DividendAmount = ISNULL(@dividendAmount, DividendAmount),
	Frequency = ISNULL(@frequency, Frequency),
	DividendType = ISNULL(@dividendType, DividendType)
	WHERE SecurityId=@securityId

		
	
END